/**
 * Generates `public/sitemap.xml` and `public/robots.txt` from the SEO route list.
 *
 * Usage:
 *   pnpm sitemap
 *
 * Runs automatically before `pnpm build`.
 *
 * When you add a new public page:
 * 1. Add a route in `src/App.tsx`
 * 2. Add metadata in `src/data/seo.ts` (`SEO` map), OR ensure it is covered by
 *    program detail generation via `PROGRAM_DETAILS`
 * 3. Re-run `pnpm sitemap` (or `pnpm build`)
 *
 * Location landing pages are included via `SEO` / `getIndexablePaths()`
 * (see docs/SEO.md).
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

const DEFAULT_SITE_URL = 'https://www.unitedbba.com'

function getSiteUrl(): string {
  const fromEnv = (process.env.VITE_SITE_URL ?? process.env.SITE_URL ?? '').trim()
  if (fromEnv) return fromEnv.replace(/\/+$/, '')
  return DEFAULT_SITE_URL
}

function absoluteUrl(base: string, path: string): string {
  if (!path || path === '/') return `${base}/`
  return `${base}${path.startsWith('/') ? path : `/${path}`}`
}

async function main() {
  // Dynamic import keeps this script aligned with the app's indexable paths.
  const { getIndexablePaths } = await import('../src/data/seo.ts')
  const siteUrl = getSiteUrl()
  const paths = getIndexablePaths()
  const today = new Date().toISOString().slice(0, 10)

  const urlEntries = paths
    .map((path) => {
      const loc = absoluteUrl(siteUrl, path)
      const priority =
        path === '/'
          ? '1.0'
          : path.startsWith('/programs/') || path === '/contact'
            ? '0.8'
            : '0.6'
      const changefreq = path === '/' ? 'weekly' : 'monthly'
      return `  <url>
    <loc>${loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`
    })
    .join('\n')

  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries}
</urlset>
`

  const robots = `# robots.txt — United Black Belt Academy
# Regenerated by \`pnpm sitemap\`. Set VITE_SITE_URL before build in production.

User-agent: *
Allow: /

# SPA client routes only — do not disallow legitimate marketing pages.
# Disallow API if ever co-hosted on the same origin:
Disallow: /api/

Sitemap: ${absoluteUrl(siteUrl, '/sitemap.xml')}
`

  const publicDir = join(root, 'public')
  mkdirSync(publicDir, { recursive: true })
  writeFileSync(join(publicDir, 'sitemap.xml'), sitemap, 'utf8')
  writeFileSync(join(publicDir, 'robots.txt'), robots, 'utf8')

  console.log(
    `Wrote public/sitemap.xml (${paths.length} URLs) and public/robots.txt for ${siteUrl}`,
  )
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
